apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

vpc:
  id: vpc-03a96b10d8689403c
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-05339de676c1f7a9b
      my-new-stack-PublicSubnet02:
        id: subnet-012b6457dc0cb7aa8
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-0993f43e3c0461507
      my-new-stack-PrivateSubnet02:
        id: subnet-0de995ae20cd31121

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.micro
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: true
