name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and package with Maven
        run: |
          echo 'Code Compilation is starting'
          mvn clean compile
          echo 'Code Compilation is completed'
          echo 'Code Packing is starting'
          mvn clean package
          echo 'Code Packing is completed'

      - name: Building & Tagging Docker Image
        run: |
          echo 'Starting Building Docker Image'
          docker build -t shubhamveer111/flipkart-ms .
          docker build -t flipkart-ms .
          echo 'Completed Building Docker Image'

      - name: Docker push to Docker Hub
        run: |
          echo "Push Docker Image to DockerHub : In Progress"
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login docker.io -u shubhamveer111 --password-stdin
          docker push shubhamveer111/flipkart-ms:latest
          echo "Push Docker Image to DockerHub : Completed"
          whoami
